##-- Experiment info exp_run_config --##
# experiment name. Keep it unique.
exp_name: exp0003_c3d_ucf101_grayscale
use_test: True
n_test_interval: 20
if_pretrain: False


##-- Dataset exp_run_config --##
# the path of the index csv file of the used data (like UCF101's csv file).
# The original file is : 'ucf101.csv'
data_path: /home/pingao/datasets/ucf101_as_frames
dataset: ucf101
n_classes: 16
n_workers: 4


##-- Load saved model exp_run_config --##
resume_model_path:
resume_epoch: 0


##-- Model exp_run_config --##
model_name: C3D
batch_size: 8
snapshot: 10
max_epoch: 400

init_learning_rate: 0.00001
scheduler_step_size: 100
scheduler_gamma: 0.5
momentum: 0.9
wd: 0

