##-- Experiment info exp_run_config --##
# experiment name. Keep it unique.
exp_name: exp000_template
use_test: True
n_test_interval: 20
if_pretrain: False


##-- Dataset exp_run_config --##
# the path of the index csv file of the used data (like UCF101's csv file).
# The original file is : 'ucf101.csv'
data_path: data/ucf101_motion_mini
dataset: ucf101
n_workers: 8


##-- Load saved model exp_run_config --##
resume_model_path:
resume_epoch: 0


##-- Model exp_run_config --##
model_name: C3D
batch_size: 2
snapshot: 20
max_epoch: 100

init_learning_rate: 0.001
momentum: 0.9
wd: 0.0005

