##-- Experiment info exp_run_config --##
# experiment name. Keep it unique.
exp_name: exp0006_c3d_ucf101_01
use_test: True
n_test_interval: 1
if_pretrain: False


##-- Dataset exp_run_config --##
# the path of the index csv file of the used data (like UCF101's csv file).
# The original file is : 'ucf101.csv'
data_path: /home/pingao/datasets/ucf101
dataset: ucf101
n_classes: 101
n_workers: 4


##-- Load saved model exp_run_config --##
resume_model_path:
resume_epoch: 0


##-- Model exp_run_config --##
model_name: C3D
batch_size: 12
snapshot: 50
max_epoch: 100

init_learning_rate: 0.0001
scheduler_step_size: 100
scheduler_gamma: 0.1
momentum: 0.9
wd: 0.0005

