##-- Experiment info exp_run_config --##
# SGD as it in paper
# experiment name. Keep it unique.
exp_name: exp0008_seizurev17_adam_02
use_test: True
n_test_interval: 10
if_pretrain: False


##-- Dataset exp_run_config --##
# the path of the index csv file of the used data (like UCF101's csv file).
# The original file is : 'ucf101.csv'
data_path: /opt/pingao/dataset/dataset_seizure_v17
dataset: ucf101
n_classes: 2
n_workers: 4


##-- Load saved model exp_run_config --##
resume_model_path:
resume_epoch: 0


##-- Model exp_run_config --##
model_name: C3D
batch_size: 24
snapshot: 50
max_epoch: 400

clip_len: 16
gray_scale: True
optimizer: Adam

init_learning_rate: 0.0003
scheduler_step_size: 100
scheduler_gamma: 0.5
momentum: 0.9
wd: 0.001

